### ISSUE TITLE
Not working with C code

### ISSUE THREAD

**Issue by Grumpy-Mike** [martinkooij/pi-pico-ss-oled#1]
Thanks for responding on the mag Pi forum. You can get the code I am trying with this link

Please delete this post or link after you have got it as I need to keep this code confidential until it goes public in a month or so.
Thanks again.
P.S. I had always thought there were private messages on that forum but I couldn't find a way to send one.

**Comment by martinkooij** [comment]
I did a quick look at your code, most was OK, I found some minor things, and also I found that the i2c1 hardware component of Pi Pico was executed  via a NULL or random pointer ;). I did set the i2c component on some other place in the C++ code, and it got lost in translating from C-> C++ and back again ;).  Let us hope this was the main cause!!! 

_C file structure_
-	In any .c file you only need to include the header (.h) file with the type definitions and the function definitions that you will be using in the .c file. The actual function code and (global) variable are defined in .c code files. I restructured the *.c files and the *.h files tot that effect.
-	 When doing this I found that the *.c and the *.h files contained double, none, or the wrong definitions, partly because the way I earlier changed the code to work my encapsulated library. I have changed it back and I think it should be OK now. 
-	Setting the correct I2C component, number 1 or 2, on the PICO had been forgotten in the init code. In practice this means that the I2C was never started correctly. I added a define ( #define PICO_I2C i2c1) to ss_oled.c and used that macro defne in the oledINIT code of ss_oled.c. Note that you can now only use pins for the oled that are connected to i2c1, unless you change the define. You are allright with pin 14 and 15. 
-	It compiles(!). I have *not* tested it on any pico as I am currently not at home. You can see or yourself, maybe. 
-	Dependency graphs
o	Ss_oled.h -> pico-gm-oled.c
o	BitBang_I2C.h -> ss_oled.h -> ss_oled.c
o	BitBang_I2C.h -> BitBang_I2C.c

_CMakefile structure_
-	Add executables and/or libraries to a project. 
-	I made two examples that produces *exactly* the same code. 
o	**A.** where all .c files are in one directory, and everything is compiled together. (note that I separated the header files in a separate include directory, and told CMake to look there. You could skip that as well and put all files (.c and .h files) together in one directory. In that case you don’t need the **target_include_files()** directive in CMakeLists.txt. 
o	**B.** where the Bitbang and the ss_oled .c files are separated in a library. In that case the top level CMakeFiles.txt contains
	                              - a reference to that (INTERFACE type) library (**add_subdirectory()**)
	                              - includes the library in the project (**target_include_libraries()**)
-	Both examples are the same, it is a matter of taste. I personally like the fact that if you will not be using the hardware_i2c library in your pico-gm-oled.c code you don’t need to mention that in the top level CMakeFile.txt, but that is a bit of a fad, I have to admit. 


drop a line to martin (dot) kooij (dot) 4 (at) gmail (dot) com for a link to the code with some comments ;).

**Comment by martinkooij** [comment]
Issue solved, this wrapper C++ only.
